config/routes.rb
Rtcg::Application.routes.draw do |map|
  resources :careers

  resources :motivations

  resources :trials_and_travails

  resources :birthrights

  resources :lure_of_the_voids

  resources :home_worlds

  resources :characters

  resources :roles

  devise_for :users

  root :to => "characters#index"

end

app/models/character.rb
class Character < ActiveRecord::Base
  attr_accessible :name, :user_id, :experience_to_spend, :experience_spent, :id,
    :weapon_skill, :ballistic_skill, :strength, :toughness, :agility, :intelligence, :perception, :will_power,
    :fellowship, :home_world_id, :lure_of_the_void_id, :motivation_id, :birthright_id, :career_id, :trials_and_travails_id,
    :gender
  attr_writer :current_step
  
  belongs_to :user
  belongs_to :home_world
  belongs_to :birthright
  belongs_to :career
  belongs_to :lure_of_the_void
  belongs_to :motivation
  belongs_to :trials_and_travails
  
  validates_presence_of :name, :if => lambda { |c| c.current_step == "attributes" }
  validates_presence_of :weapon_skill, :if => lambda { |c| c.current_step == "attributes" }
  validates_presence_of :ballistic_skill, :if => lambda { |c| c.current_step == "attributes" }
  validates_presence_of :strength, :if => lambda { |c| c.current_step == "attributes" }
  validates_presence_of :toughness, :if => lambda { |c| c.current_step == "attributes" }
  validates_presence_of :agility, :if => lambda { |c| c.current_step == "attributes" }
  validates_presence_of :intelligence, :if => lambda { |c| c.current_step == "attributes" }
  validates_presence_of :perception, :if => lambda { |c| c.current_step == "attributes" }
  validates_presence_of :will_power, :if => lambda { |c| c.current_step == "attributes" }
  validates_presence_of :fellowship, :if => lambda { |c| c.current_step == "attributes" }
  validates_presence_of :gender, :if => lambda { |c| c.current_step == "attributes" }
  validates_uniqueness_of :name, :if => lambda { |c| c.current_step == "attributes" }
  validates_length_of :name, :if => lambda { |c| c.current_step == "attributes" },
    :within => 4..60,
    :too_long => 'must be sixty characters or less.',
    :too_short => 'must be four characters or more.'
    
  validates_presence_of :home_world_id, :if => lambda { |c| c.current_step == "origins" }
  validates_presence_of :lure_of_the_void_id, :if => lambda { |c| c.current_step == "origins" }
  validates_presence_of :motivation_id, :if => lambda { |c| c.current_step == "origins" }
  validates_presence_of :trials_and_travails_id, :if => lambda { |c| c.current_step == "origins" }
  validates_presence_of :birthright_id, :if => lambda { |c| c.current_step == "origins" }
  validates_presence_of :career_id, :if => lambda { |c| c.current_step == "origins" }
  
  def self.generate_stat
    new_stat = 27 + rand(10) + rand(10)
  end
  
  def self.career_rank(experience_spent)
    case experience_spent
      when 0..4999
        '0'
      when 5000..6999
        '1'
      when 7000..9999
        '2'
      when 10000..12999
        '3'
      when 13000..16999
        '4'
      when 17000..20999
        '5'
      when 21000..24999
        '6'
      when 25000..29999
        '7'
      else '8'
    end
  end
  
  def steps
    %w[attributes origins]
  end
  
  def current_step
    @current_step || steps.first
  end
  
  def next_step
    self.current_step = steps[steps.index(current_step)+1]
  end
  
  def previous_step
    self.current_step = steps[steps.index(current_step)-1]
  end
  
  def first_step?
    current_step == steps.first
  end
  
  def last_step?
    current_step == steps.last
  end
  
  def all_valid?
    steps.all? do |step|
      self.current_step = step
      valid?
    end
  end
end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController

  load_and_authorize_resource

  def index
    @characters = Character.all
  end
  
  def show
  end
  
  def new
    session[:character_params] = {}
    @character.user_id = current_user.id
    @character.weapon_skill = Character.generate_stat
    @character.ballistic_skill = Character.generate_stat
    @character.strength = Character.generate_stat
    @character.toughness = Character.generate_stat
    @character.agility = Character.generate_stat
    @character.intelligence = Character.generate_stat
    @character.perception = Character.generate_stat
    @character.will_power = Character.generate_stat
    @character.fellowship = Character.generate_stat
  end
  
  def create
    session[:character_params].deep_merge!(params[:character]) if params[:character]
    @character = Character.new(session[:character_params])
    @character.current_step = session[:character_step]
    if @character.valid?
      if params[:back_button]
        @character.previous_step
      elsif @character.last_step?
        @character.save if @character.all_valid?
      else
        @character.next_step
      end
    else
      session[:character_step] = @character.current_step
    end
    if @character.new_record?
      render "new"
    else
      session[:character_step] = session[:character_params] = nil
      flash[:notice] = "Character saved"
      redirect_to @character
    end
    session[:character_step] = @character.current_step
  end
  
  def edit
  end
  
  def update
    if @character.update_attributes(params[:character])
      flash[:notice] = "Successfully updated character."
      redirect_to @character
    else
      render :action => 'edit'
    end
  end
  
  def destroy
    @character.destroy
    flash[:notice] = "Successfully destroyed character."
    redirect_to characters_url
  end
end

app/helpers/characters_helper.rb
module CharactersHelper
end

app/views/characters/_attributes_step.erb
    <h2>Attributes</h2>
    <%= f.input :name %>
    <%= f.input :gender, :as => :select, :collection => ["Male", "Female"] %>
    <%= f.input :weapon_skill, :label => 'Weapon Skill', 
      :required => false, :input_html => { :disabled => true, :size => 3 } %>
    <%= f.input :ballistic_skill, :label => 'Ballistic Skill', 
      :required => false, :input_html => { :disabled => true, :size => 3 } %>
    <%= f.input :strength, :label => 'Strength', 
      :required => false, :input_html => { :disabled => true, :size => 3 } %>
    <%= f.input :toughness, :label => 'Toughness', 
      :required => false, :input_html => { :disabled => true, :size => 3 } %>
    <%= f.input :agility, :label => 'Agility', 
      :required => false, :input_html => { :disabled => true, :size => 3 } %>
    <%= f.input :intelligence, :label => 'Intelligence', 
      :required => false, :input_html => { :disabled => true, :size => 3 } %>
    <%= f.input :perception, :label => 'Perception', 
      :required => false, :input_html => { :disabled => true, :size => 3 } %>
    <%= f.input :will_power, :label => 'Will Power', 
      :required => false, :input_html => { :disabled => true, :size => 3 } %>
    <%= f.input :fellowship, :label => 'Fellowship', 
      :required => false, :input_html => { :disabled => true, :size => 3 } %>
      
    <%= hidden_field :character, :user_id, :value => @character.user_id %>
    <%= hidden_field :character, :weapon_skill, :value => @character.weapon_skill %>
    <%= hidden_field :character, :ballistic_skill, :value => @character.ballistic_skill %>
    <%= hidden_field :character, :strength, :value => @character.strength %>
    <%= hidden_field :character, :toughness, :value => @character.toughness %>
    <%= hidden_field :character, :agility, :value => @character.agility %>
    <%= hidden_field :character, :intelligence, :value => @character.intelligence %>
    <%= hidden_field :character, :perception, :value => @character.perception %>
    <%= hidden_field :character, :will_power, :value => @character.will_power %>
    <%= hidden_field :character, :fellowship, :value => @character.fellowship %>

app/views/characters/_form.html.erb
<%= semantic_form_for @character do |f| %>
  <% f.inputs do %>
    <%= render "#{@character.current_step}_step", :f => f %>
  <% end %>
  <%= f.submit "Back", :name => "back_button" unless @character.first_step? %> 
  <%= f.submit "Continue" unless @character.last_step? %>
  <%= f.submit "Complete" if @character.last_step? %>
<% end %>

app/views/characters/_origins_step.erb
    <h2>Origin Path</h2>
    <%= f.input :home_world %>
    <%= f.input :birthright %>
    <%= f.input :lure_of_the_void %>
    <%= f.input :trials_and_travails %>
    <%= f.input :motivation %>
    <%= f.input :career %>

app/views/characters/edit.html.erb
<% title "Edit Character" %>

<%= render 'form' %>

<p>
  <% if can? :read, @character %>
    <%= link_to "Show", @character %> |
  <% end %>
  <%= link_to "View All", characters_path %>
</p>

app/views/characters/index.html.erb
<% title "Characters" %>

<table>
  <tr>
    <th>Name</th>
    <th>User</th>
    <th>Career Rank</th>
    <th>Experience To Spend</th>
    <th>Experience Spent</th>
    
  </tr>
  <% for character in @characters %>
    <tr>
      <td><%= character.name %></td>
      <td><%= character.user.username.capitalize %></td>
      <td><%= Character.career_rank(character.experience_spent) %></td>
      <td><%= character.experience_to_spend %></td>
      <td><%= character.experience_spent %></td>
      <% if can? :read, character %>
        <td><%= link_to "Show", character %></td>
      <% end %>
      <% if can? :update, character %>
        <td><%= link_to "Edit", edit_character_path(character) %></td>
      <% end %>
      <% if can? :destroy, character %>
        <td><%= link_to "Destroy", character, :confirm => 'Are you sure?', :method => :delete %></td>
      <% end %>
    </tr>
  <% end %>
</table>

<% if can? :create, Character %>
  <p><%= link_to "New Character", new_character_path %></p>
<% end %>

app/views/characters/new.html.erb
<% title "New Character" %>

<%= render 'form' %>

<p><%= link_to "Back to List", characters_path %></p>

app/views/characters/show.html.erb
<% title "Character" %>

<p>
  <strong>Name:</strong>
  <%= @character.name %>
</p>
<p>
  <strong>User:</strong>
  <%= @character.user.username.capitalize %>
</p>
<p>
  <strong>Weapon Skill:</strong>
  <%= @character.weapon_skill %>
</p>
<p>
  <strong>Ballistic Skill:</strong>
  <%= @character.ballistic_skill %>
</p>
<p>
  <strong>Strength:</strong>
  <%= @character.strength %>
</p>
<p>
  <strong>Toughness:</strong>
  <%= @character.toughness %>
</p>
<p>
  <strong>Agility:</strong>
  <%= @character.agility %>
</p>
<p>
  <strong>Intelligence:</strong>
  <%= @character.intelligence %>
</p>
<p>
  <strong>Perception:</strong>
  <%= @character.perception %>
</p>
<p>
  <strong>Will Power:</strong>
  <%= @character.will_power %>
</p>
<p>
  <strong>Fellowship:</strong>
  <%= @character.fellowship %>
</p>
<p>
  <strong>Experience To Spend:</strong>
  <%= @character.experience_to_spend %>
</p>
<p>
  <strong>Experience Spent:</strong>
  <%= @character.experience_spent %>
</p>

<p>
  <% if can? :update, @character %>
    <%= link_to "Edit", edit_character_path(@character) %> |
  <% end %>
  <% if can? :destroy, @character %>
    <%= link_to "Destroy", @character, :confirm => 'Are you sure?', :method => :delete %> |
  <% end %>
  <%= link_to "View All", characters_path %>
</p>